[package]
authors.workspace      = true
categories             = ["network-programming"]
description            = "rust-libp2p based p2p transport implementation"
edition.workspace      = true
homepage.workspace     = true
include                = ["Cargo.toml", "LICENSE", "README.md", "src/**/*.rs", "tests/**/*.rs"]
keywords               = ["hopr", "libp2p", "p2p", "transport"]
license.workspace      = true
name                   = "hopr-transport-p2p"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.9.4"

[lib]
crate-type = ["rlib"]

[features]
default        = []
runtime-tokio  = ["libp2p/tokio"]
telemetry      = ["dep:lazy_static", "hopr-api/types-telemetry"]
testing        = []
transport-quic = ["dep:quinn-udp", "libp2p/quic"]

[dependencies]
async-broadcast = { workspace = true }
async-trait = { workspace = true }
backon = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true, optional = true }
libp2p = { workspace = true, features = [
  "autonat",
  "dns",
  "identify",
  "macros",
  "noise",
  "tcp",
  "yamux",
] }
libp2p-stream = { workspace = true }
multiaddr = { workspace = true }
quinn-udp = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }

dashmap     = { workspace = true }
pin-project = { workspace = true }

hopr-api   = { workspace = true, features = ["ct", "network"] }
hopr-utils = { workspace = true, features = ["network-types"] }

[target.'cfg(target_os = "macos")'.dependencies]
quinn-udp = { workspace = true, optional = true, features = [
  "fast-apple-datapath",
] }

[dev-dependencies]
anyhow           = { workspace = true }
async_channel_io = { workspace = true }
bytes            = { workspace = true }
lazy_static      = { workspace = true }
more-asserts     = { workspace = true }
tokio            = { workspace = true }

hopr-api = { workspace = true, features = ["graph", "network", "types-random"] }

hopr-utils = { workspace = true, features = ["platform"] }

[package.metadata.cargo-shear]
ignored = ["quinn-udp"]

[package.metadata.cargo-machete]
ignored = ["quinn-udp"]
