//! The discovery mechanism uses an external stimulus to trigger the discovery
//! process on the libp2p side. It is responsible for processing the events
//! generated by other components and passing them to the libp2p swarm in
//! an appropriate format.
use std::{
    cmp::{Ordering, Reverse},
    collections::{BinaryHeap, HashMap, VecDeque},
};

use backon::BackoffBuilder;
use futures::stream::{BoxStream, Stream, StreamExt};
use libp2p::{
    Multiaddr, PeerId,
    core::Endpoint,
    swarm::{
        ConnectionDenied, ConnectionId, DialError, DialFailure, NetworkBehaviour, ToSwarm, dial_opts::DialOpts,
        dummy::ConnectionHandler,
    },
};

use crate::PeerDiscovery;

/// Data structure holding the item alongside a release timemestamp.
///
/// The ordering functionality is defined only over the release timestamp.
pub struct Delayed<T> {
    pub release_at: std::time::Instant,
    pub item: T,
}

impl<T> PartialEq for Delayed<T> {
    fn eq(&self, other: &Self) -> bool {
        self.release_at == other.release_at
    }
}

impl<T> PartialOrd for Delayed<T> {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl<T> Eq for Delayed<T> {}

impl<T> Ord for Delayed<T> {
    fn cmp(&self, other: &Self) -> Ordering {
        self.release_at.cmp(&other.release_at)
    }
}

impl<T> From<(std::time::Instant, T)> for Delayed<T> {
    fn from(value: (std::time::Instant, T)) -> Self {
        Self {
            release_at: value.0,
            item: value.1,
        }
    }
}

#[inline]
fn initial_backoff() -> backon::ExponentialBackoff {
    backon::ExponentialBuilder::new()
        .with_min_delay(std::time::Duration::from_secs(3))
        .with_max_delay(std::time::Duration::from_secs(120))
        .with_factor(1.5)
        .with_jitter()
        .without_max_times()
        .build()
}

pub struct Behaviour {
    me: PeerId,
    events: BoxStream<'static, PeerDiscovery>,
    pending_events: VecDeque<
        libp2p::swarm::ToSwarm<
            <Self as NetworkBehaviour>::ToSwarm,
            <<Self as NetworkBehaviour>::ConnectionHandler as libp2p::swarm::ConnectionHandler>::FromBehaviour,
        >,
    >,
    bootstrap_peers: HashMap<PeerId, Vec<Multiaddr>>,
    connected_peers: HashMap<PeerId, usize>,
    next_dial_attempts: BinaryHeap<Reverse<Delayed<PeerId>>>,
    not_connected_peers: HashMap<PeerId, backon::ExponentialBackoff>,
}

impl Behaviour {
    pub fn new<T>(me: PeerId, external_discovery_events: T) -> Self
    where
        T: Stream<Item = PeerDiscovery> + Send + 'static,
    {
        Self {
            me,
            events: Box::pin(external_discovery_events),
            bootstrap_peers: HashMap::new(),
            pending_events: VecDeque::new(),
            connected_peers: HashMap::new(),
            next_dial_attempts: BinaryHeap::with_capacity(1500),
            not_connected_peers: HashMap::new(),
        }
    }

    fn has_known_address(&self, peer: &PeerId) -> bool {
        self.bootstrap_peers
            .get(peer)
            .is_some_and(|addresses| !addresses.is_empty())
    }

    fn has_scheduled_dial(&self, peer: &PeerId) -> bool {
        self.next_dial_attempts.iter().any(|entry| entry.0.item == *peer)
    }

    fn cancel_dial(&mut self, peer: &PeerId) {
        self.not_connected_peers.remove(peer);
        self.next_dial_attempts.retain(|entry| entry.0.item != *peer);
    }

    fn schedule_dial_with(&mut self, peer: PeerId, mut backoff: backon::ExponentialBackoff) {
        if !self.has_known_address(&peer) || self.has_scheduled_dial(&peer) {
            return;
        }

        let duration = backoff.next().unwrap_or_else(|| {
            tracing::debug!(%peer, "failed to get next backoff duration, using 10s");
            std::time::Duration::from_secs(10)
        });
        self.not_connected_peers.insert(peer, backoff);
        self.next_dial_attempts.push(Reverse(Delayed {
            release_at: std::time::Instant::now() + duration,
            item: peer,
        }));
    }
}

impl NetworkBehaviour for Behaviour {
    type ConnectionHandler = ConnectionHandler;
    type ToSwarm = ();

    #[tracing::instrument(
        level = "debug",
        name = "Discovery::handle_established_inbound_connection",
        skip(self),
        fields(transport = "p2p discovery"),
        err(Display)
    )]
    fn handle_established_inbound_connection(
        &mut self,
        connection_id: libp2p::swarm::ConnectionId,
        peer: libp2p::PeerId,
        local_addr: &libp2p::Multiaddr,
        remote_addr: &libp2p::Multiaddr,
    ) -> Result<libp2p::swarm::THandler<Self>, libp2p::swarm::ConnectionDenied> {
        Some(Self::ConnectionHandler {}).ok_or_else(|| {
            libp2p::swarm::ConnectionDenied::new(crate::errors::P2PError::Logic(format!(
                "Connection from '{peer}' is not allowed"
            )))
        })
    }

    #[tracing::instrument(
        level = "debug",
        name = "Discovery::handle_pending_outbound_connection"
        skip(self),
        fields(transport = "p2p discovery"),
        ret(Debug),
        err(Display)
    )]
    fn handle_pending_outbound_connection(
        &mut self,
        connection_id: ConnectionId,
        maybe_peer: Option<PeerId>,
        addresses: &[Multiaddr],
        effective_role: Endpoint,
    ) -> Result<Vec<Multiaddr>, ConnectionDenied> {
        if let Some(peer) = maybe_peer {
            // inject the multiaddress of the peer for possible dial usage by stream protocols
            return Ok(self
                .bootstrap_peers
                .get(&peer)
                .map_or(vec![], |addresses| addresses.clone()));
        }

        Ok(vec![])
    }

    #[tracing::instrument(
        level = "trace",
        name = "Discovery::handle_established_outbound_connection",
        skip(self),
        fields(transport = "p2p discovery"),
        err(Display)
    )]
    fn handle_established_outbound_connection(
        &mut self,
        connection_id: libp2p::swarm::ConnectionId,
        peer: libp2p::PeerId,
        addr: &libp2p::Multiaddr,
        role_override: libp2p::core::Endpoint,
        port_use: libp2p::core::transport::PortUse,
    ) -> Result<libp2p::swarm::THandler<Self>, libp2p::swarm::ConnectionDenied> {
        Ok(Self::ConnectionHandler {})
    }

    #[tracing::instrument(
        level = "debug",
        name = "Discovery::on_swarm_event"
        skip(self),
        fields(transport = "p2p discovery"),
    )]
    fn on_swarm_event(&mut self, event: libp2p::swarm::FromSwarm) {
        match event {
            libp2p::swarm::FromSwarm::ConnectionEstablished(data) => {
                *self.connected_peers.entry(data.peer_id).or_insert(0) += 1;
                self.cancel_dial(&data.peer_id);
            }
            libp2p::swarm::FromSwarm::ConnectionClosed(data) => {
                let v = self.connected_peers.entry(data.peer_id).or_insert(0);
                if *v > 0 {
                    *v -= 1;
                }

                let has_no_more_live_connections = *v == 0;

                if has_no_more_live_connections {
                    self.connected_peers.remove(&data.peer_id);
                    // Guard against duplicate heap entries: if a stale schedule_dial_with
                    // call (e.g. from a racing Announce) already enqueued this peer, the
                    // existing backoff entry will handle the reconnect.
                    if !self.not_connected_peers.contains_key(&data.peer_id) {
                        self.schedule_dial_with(data.peer_id, initial_backoff());
                    }
                }
            }
            libp2p::swarm::FromSwarm::DialFailure(DialFailure { peer_id, error, .. }) => {
                tracing::debug!(?peer_id, %error, "Failed to dial peer");

                // on a failed dial get the next scheduled dial using the backoff,
                // but only if the peer isn't connected, has a known address, the
                // failure is transient (not `DialError::NoAddresses`), and no dial
                // is already queued; otherwise cancel any pending retry until the
                // peer is announced again.
                if let Some(peer) = peer_id {
                    if self.connected_peers.contains_key(&peer)
                        || matches!(error, DialError::NoAddresses)
                        || !self.has_known_address(&peer)
                    {
                        self.cancel_dial(&peer);
                    } else if !self.has_scheduled_dial(&peer) {
                        let backoff = self.not_connected_peers.remove(&peer).unwrap_or_else(|| {
                            tracing::debug!(%peer, "no backoff for a failed dial, creating new backoff");
                            initial_backoff()
                        });
                        self.schedule_dial_with(peer, backoff);
                    }
                }
            }
            _ => {}
        }
    }

    fn on_connection_handler_event(
        &mut self,
        _peer_id: libp2p::PeerId,
        _connection_id: libp2p::swarm::ConnectionId,
        _event: libp2p::swarm::THandlerOutEvent<Self>,
    ) {
        // Nothing is necessary here, because no ConnectionHandler events should be generated
    }

    #[tracing::instrument(
        level = "debug",
        name = "Discovery::poll"
        skip(self, cx),
        fields(transport = "p2p discovery")
    )]
    fn poll(
        &mut self,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<libp2p::swarm::ToSwarm<Self::ToSwarm, libp2p::swarm::THandlerInEvent<Self>>> {
        if let Some(value) = self.pending_events.pop_front() {
            return std::task::Poll::Ready(value);
        };

        let poll_result = self.events.poll_next_unpin(cx).map(|e| {
            if let Some(PeerDiscovery::Announce(peer, multiaddresses)) = e
                && peer != self.me
            {
                tracing::debug!(%peer, addresses = ?&multiaddresses, "Announcement");

                for multiaddress in &multiaddresses {
                    self.pending_events.push_back(ToSwarm::NewExternalAddrOfPeer {
                        peer_id: peer,
                        address: multiaddress.clone(),
                    });
                }

                // Store announced addresses for later dialing / protocol use.
                // Only schedule a dial if the peer is not already connected and not
                // already queued: multiple rapid announcements for the same disconnected
                // peer must not stack up N heap entries that all fire simultaneously,
                // issuing N concurrent dials and perpetuating a dial storm.
                if !multiaddresses.is_empty() {
                    self.bootstrap_peers.insert(peer, multiaddresses);
                    if !self.connected_peers.contains_key(&peer) && !self.not_connected_peers.contains_key(&peer) {
                        self.schedule_dial_with(peer, initial_backoff());
                    }
                }
            }
        });

        if matches!(poll_result, std::task::Poll::Ready(_))
            && let Some(value) = self.pending_events.pop_front()
        {
            return std::task::Poll::Ready(value);
        }

        let now = std::time::Instant::now();
        while self
            .next_dial_attempts
            .peek()
            .map(|x| x.0.release_at <= now)
            .unwrap_or(false)
        {
            let peer = self
                .next_dial_attempts
                .pop()
                .expect("The value should be present within the same access")
                .0
                .item;

            // Skip stale entries (peer reconnected or was otherwise unscheduled)
            if !self.not_connected_peers.contains_key(&peer) {
                continue;
            }

            // Dial only the addresses HOPR discovery announced for this peer. Passing
            // explicit addresses leaves `extend_addresses_through_behaviour` at its
            // default of `false`, so other behaviours (e.g. autonat's address cache,
            // which may hold a peer-advertised loopback address pointing at us) cannot
            // inject additional dial targets.
            //
            // A scheduled peer always has a non-empty `bootstrap_peers` entry
            // (`schedule_dial_with` enforces `has_known_address`). Guard the invariant
            // anyway: dialing with an empty address set would fail `NoAddresses` and be
            // silently cancelled, so surface it as a warning and drop the schedule.
            let Some(addresses) = self.bootstrap_peers.get(&peer).cloned().filter(|a| !a.is_empty()) else {
                tracing::warn!(%peer, "scheduled dial for a peer without a known address, dropping schedule");
                self.cancel_dial(&peer);
                continue;
            };
            tracing::trace!(%peer, "attempting a new dial attempt item");
            self.pending_events.push_back(ToSwarm::Dial {
                opts: DialOpts::peer_id(peer).addresses(addresses).build(),
            });
        }

        if let Some(value) = self.pending_events.pop_front() {
            std::task::Poll::Ready(value)
        } else {
            std::task::Poll::Pending
        }
    }
}

#[cfg(test)]
mod tests {
    use futures::stream;
    use libp2p::{
        Multiaddr,
        core::{ConnectedPoint, Endpoint},
        swarm::{
            ConnectionId, FromSwarm,
            behaviour::{ConnectionClosed, ConnectionEstablished, DialFailure},
        },
    };

    use super::*;

    fn make_behaviour() -> Behaviour {
        Behaviour::new(PeerId::random(), stream::empty())
    }

    fn connected_point() -> ConnectedPoint {
        ConnectedPoint::Dialer {
            address: "/ip4/127.0.0.1/tcp/9000".parse::<Multiaddr>().unwrap(),
            role_override: Endpoint::Dialer,
            port_use: libp2p::core::transport::PortUse::Reuse,
        }
    }

    fn simulate_established(b: &mut Behaviour, peer: PeerId) {
        let endpoint = connected_point();
        b.on_swarm_event(FromSwarm::ConnectionEstablished(ConnectionEstablished {
            peer_id: peer,
            connection_id: ConnectionId::new_unchecked(0),
            endpoint: &endpoint,
            failed_addresses: &[],
            other_established: 0,
        }));
    }

    fn simulate_closed(b: &mut Behaviour, peer: PeerId, remaining: usize) {
        let endpoint = connected_point();
        b.on_swarm_event(FromSwarm::ConnectionClosed(ConnectionClosed {
            peer_id: peer,
            connection_id: ConnectionId::new_unchecked(0),
            endpoint: &endpoint,
            cause: None,
            remaining_established: remaining,
        }));
    }

    fn simulate_dial_failure(b: &mut Behaviour, peer: PeerId, error: &DialError) {
        b.on_swarm_event(FromSwarm::DialFailure(DialFailure {
            peer_id: Some(peer),
            error,
            connection_id: ConnectionId::new_unchecked(0),
        }));
    }

    fn announce(b: &mut Behaviour, peer: PeerId) {
        let addr: Multiaddr = "/ip4/127.0.0.1/tcp/9000".parse().unwrap();
        // Mirrors the Announce branch in poll(): only schedule if not connected
        // AND not already enqueued, to match the heap-deduplication invariant.
        b.bootstrap_peers.insert(peer, vec![addr]);
        if !b.connected_peers.contains_key(&peer) && !b.not_connected_peers.contains_key(&peer) {
            b.schedule_dial_with(peer, initial_backoff());
        }
    }

    #[test]
    fn initial_backoff_continues_at_max_delay() {
        let max_delay = std::time::Duration::from_secs(120);
        let delays = initial_backoff().take(20).collect::<Vec<_>>();

        assert_eq!(
            delays.len(),
            20,
            "peer discovery backoff must not stop producing delays"
        );

        let mut base_delay = std::time::Duration::from_secs(3);
        for (attempt, delay) in delays.into_iter().enumerate() {
            assert!(
                delay >= base_delay && delay < base_delay.saturating_mul(2),
                "attempt {attempt} delay {delay:?} must include jitter based on {base_delay:?}"
            );
            base_delay = base_delay.mul_f32(1.5).min(max_delay);
        }

        assert_eq!(base_delay, max_delay);
    }

    // ── regression: announce must not re-enqueue dial for a connected peer ──

    /// Before the fix, every `PeerDiscovery::Announce` for an already-connected
    /// peer would call `schedule_dial_with`, which unconditionally inserts the
    /// peer into `not_connected_peers`.  The stale-skip guard in `poll()` then
    /// races with the reconnect queue and issues spurious dials.
    #[test]
    fn announce_does_not_schedule_dial_for_connected_peer() {
        let mut b = make_behaviour();
        let peer = PeerId::random();

        simulate_established(&mut b, peer);
        assert!(b.connected_peers.contains_key(&peer));
        assert!(!b.not_connected_peers.contains_key(&peer));

        // Announce the peer again (as happens continuously from the network graph).
        announce(&mut b, peer);

        assert!(
            !b.not_connected_peers.contains_key(&peer),
            "connected peer must not be added to not_connected_peers on re-announce"
        );
    }

    /// A disconnected peer that gets re-announced must still be scheduled for dialing.
    #[test]
    fn announce_schedules_dial_for_disconnected_peer() {
        let mut b = make_behaviour();
        let peer = PeerId::random();

        announce(&mut b, peer);

        assert!(
            b.not_connected_peers.contains_key(&peer),
            "disconnected peer must be queued for dialing on announce"
        );
    }

    // ── regression: DialFailure must not re-enqueue if peer is now connected ──

    /// Before the fix, a `DialFailure` for a peer that had already established
    /// an inbound connection (racing with our outbound dial) would call
    /// `schedule_dial_with` and insert the peer back into `not_connected_peers`,
    /// triggering a further dial storm.
    #[test]
    fn dial_failure_does_not_reschedule_already_connected_peer() {
        let mut b = make_behaviour();
        let peer = PeerId::random();

        // Peer connects inbound while our outbound dial is in flight.
        simulate_established(&mut b, peer);
        // Outbound dial fails after the inbound connection is up.
        simulate_dial_failure(&mut b, peer, &DialError::NoAddresses);

        assert!(
            !b.not_connected_peers.contains_key(&peer),
            "DialFailure for an already-connected peer must not re-enqueue a dial"
        );
        assert!(
            b.next_dial_attempts.iter().all(|entry| entry.0.item != peer),
            "DialFailure for an already-connected peer must cancel queued dials"
        );
    }

    /// A transient dial failure for a known peer that is genuinely not connected must reschedule.
    #[test]
    fn dial_failure_reschedules_genuinely_disconnected_peer() {
        let mut b = make_behaviour();
        let peer = PeerId::random();
        let address = "/ip4/127.0.0.1/tcp/9000".parse().unwrap();

        b.bootstrap_peers.insert(peer, vec![address]);
        // Keep the backoff as it would be while the emitted dial is in flight.
        b.not_connected_peers.insert(peer, initial_backoff());
        simulate_dial_failure(&mut b, peer, &DialError::Transport(vec![]));

        assert!(
            b.not_connected_peers.contains_key(&peer),
            "DialFailure for a disconnected peer must reschedule a dial attempt"
        );
        assert_eq!(b.next_dial_attempts.len(), 1);
    }

    #[test]
    fn dial_failure_without_address_does_not_schedule_retry() {
        let mut b = make_behaviour();
        let peer = PeerId::random();

        simulate_dial_failure(&mut b, peer, &DialError::Transport(vec![]));

        assert!(!b.not_connected_peers.contains_key(&peer));
        assert!(b.next_dial_attempts.is_empty());
    }

    #[test]
    fn no_addresses_dial_failure_cancels_retry_until_announce() {
        let peer = PeerId::random();
        let address: Multiaddr = "/ip4/127.0.0.1/tcp/9000".parse().unwrap();
        let (announcements_tx, announcements_rx) = futures::channel::mpsc::unbounded();
        let mut b = Behaviour::new(PeerId::random(), announcements_rx);

        b.not_connected_peers.insert(peer, initial_backoff());
        b.next_dial_attempts.push(Reverse(Delayed {
            release_at: std::time::Instant::now(),
            item: peer,
        }));

        simulate_dial_failure(&mut b, peer, &DialError::NoAddresses);

        assert!(!b.not_connected_peers.contains_key(&peer));
        assert!(b.next_dial_attempts.is_empty());

        announcements_tx
            .unbounded_send(PeerDiscovery::Announce(peer, vec![address]))
            .unwrap();
        let waker = futures::task::noop_waker_ref();
        let mut cx = std::task::Context::from_waker(waker);
        let _ = b.poll(&mut cx);

        assert!(b.not_connected_peers.contains_key(&peer));
        assert_eq!(b.next_dial_attempts.len(), 1);
    }

    // ── regression #31: dials carry only announced addresses ────────────────

    /// Smoke test: a scheduled dial for a peer with a known announced address is
    /// emitted for that peer.
    ///
    /// This does not, on its own, guard the #31 fix: `DialOpts` addresses and the
    /// `extend_addresses_through_behaviour` flag are `pub(crate)` to libp2p-swarm,
    /// so the address set this test cares about is not inspectable here. The fix's
    /// guarantee rests on that flag defaulting to `false` when explicit addresses
    /// are supplied (libp2p-swarm 0.47.1); the reconnection path is covered
    /// end-to-end by `disconnected_peer_reconnects_via_announced_address`.
    #[test]
    fn scheduled_dial_with_address_emits_dial_for_peer() {
        let mut b = make_behaviour();
        let peer = PeerId::random();
        let address: Multiaddr = "/ip4/127.0.0.1/tcp/9000".parse().unwrap();

        b.bootstrap_peers.insert(peer, vec![address]);
        b.not_connected_peers.insert(peer, initial_backoff());
        b.next_dial_attempts.push(Reverse(Delayed {
            release_at: std::time::Instant::now(),
            item: peer,
        }));

        let waker = futures::task::noop_waker_ref();
        let mut cx = std::task::Context::from_waker(waker);

        match b.poll(&mut cx) {
            std::task::Poll::Ready(ToSwarm::Dial { opts }) => {
                assert_eq!(opts.get_peer_id(), Some(peer));
            }
            _ => panic!("expected a Dial for the scheduled peer"),
        }
    }

    #[test]
    fn repeated_dial_failures_leave_one_pending_retry() {
        let mut b = make_behaviour();
        let peer = PeerId::random();
        let address = "/ip4/127.0.0.1/tcp/9000".parse().unwrap();

        b.bootstrap_peers.insert(peer, vec![address]);
        b.not_connected_peers.insert(peer, initial_backoff());

        simulate_dial_failure(&mut b, peer, &DialError::Transport(vec![]));
        simulate_dial_failure(&mut b, peer, &DialError::Transport(vec![]));

        assert!(b.not_connected_peers.contains_key(&peer));
        assert_eq!(b.next_dial_attempts.len(), 1);
    }

    // ── regression: repeated announces for disconnected peer must not accumulate ──

    /// Before the fix, every `PeerDiscovery::Announce` for a disconnected peer
    /// called `schedule_dial_with`, adding one heap entry per announce even though
    /// the peer was already enqueued.  At backoff expiry, all N entries fired
    /// simultaneously, issuing N concurrent dials → N DialFailure events → N new
    /// entries → repeat.
    #[test]
    fn announce_does_not_stack_dials_for_disconnected_peer() {
        let mut b = make_behaviour();
        let peer = PeerId::random();

        // First announce: peer is unknown, so a dial must be scheduled.
        announce(&mut b, peer);
        assert!(b.not_connected_peers.contains_key(&peer));
        let heap_len_after_first = b.next_dial_attempts.len();

        // Subsequent announces while peer is still not connected and already
        // enqueued must not add more heap entries.
        announce(&mut b, peer);
        announce(&mut b, peer);
        announce(&mut b, peer);

        assert_eq!(
            b.next_dial_attempts.len(),
            heap_len_after_first,
            "repeated announces for disconnected peer must not accumulate heap entries"
        );
    }

    // ── existing correct behaviour: disconnect triggers reconnect ───────────

    #[test]
    fn connection_closed_schedules_reconnect() {
        let mut b = make_behaviour();
        let peer = PeerId::random();
        let address = "/ip4/127.0.0.1/tcp/9000".parse().unwrap();

        b.bootstrap_peers.insert(peer, vec![address]);
        simulate_established(&mut b, peer);
        simulate_closed(&mut b, peer, 0);

        assert!(
            b.not_connected_peers.contains_key(&peer),
            "after disconnect with no remaining connections, peer must be queued for reconnect"
        );
    }

    #[test]
    fn connection_closed_without_address_does_not_schedule_reconnect() {
        let mut b = make_behaviour();
        let peer = PeerId::random();

        simulate_established(&mut b, peer);
        simulate_closed(&mut b, peer, 0);

        assert!(!b.not_connected_peers.contains_key(&peer));
        assert!(b.next_dial_attempts.is_empty());
    }

    #[test]
    fn connection_closed_does_not_schedule_reconnect_while_other_connections_live() {
        let mut b = make_behaviour();
        let peer = PeerId::random();

        // Two connections established.
        simulate_established(&mut b, peer);
        simulate_established(&mut b, peer);
        // One closes, one remains.
        simulate_closed(&mut b, peer, 1);

        assert!(
            !b.not_connected_peers.contains_key(&peer),
            "peer with remaining connections must not be queued for reconnect"
        );
    }
}
