[package]
authors.workspace      = true
categories             = ["network-programming"]
description            = "Full implementation of the Telemetry functionality as specified in the HOPR RFCs along with optional noise (cover traffic) generation"
edition.workspace      = true
homepage.workspace     = true
include                = ["Cargo.toml", "LICENSE", "README.md", "src/**/*.rs"]
keywords               = ["cover-traffic", "hopr", "mixnet"]
license.workspace      = true
name                   = "hopr-ct-full-network"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.3.0"

[lib]
crate-type = ["rlib"]

[features]
default = []
noise   = []
serde   = ["dep:humantime-serde", "dep:serde", "hopr-api/serde"]

[dependencies]
anyhow          = { workspace = true }
cfg-if          = { workspace = true }
futures         = { workspace = true }
futures-time    = { workspace = true }
humantime-serde = { workspace = true, optional = true }
serde           = { workspace = true, optional = true, features = ["derive"] }
smart-default   = { workspace = true }
tracing         = { workspace = true }
validator       = { workspace = true }

hopr-api = { workspace = true, features = [
  "ct",
  "graph",
  "network",
  "types-random",
] }
hopr-network-graph = { workspace = true, features = ["petgraph"] }
hopr-utils = { workspace = true, features = [
  "statistics-types",
  "statistics-types-weighted",
] }

[dev-dependencies]
lazy_static = { workspace = true }
tokio       = { workspace = true, features = ["time"] }

[package.metadata.cargo-machete]
ignored = ["humantime-serde"]
