[package]
authors.workspace = true
categories = ["algorithms", "network-programming"]
description = "Implementation of the HOPR network graph"
edition.workspace = true
homepage.workspace = true
include = [
  "Cargo.toml",
  "LICENSE",
  "README.md",
  "benches/**/*.rs",
  "src/**/*.rs",
]
keywords = ["graph", "hopr", "routing"]
license.workspace = true
name = "hopr-network-graph"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.5.0"

[lib]
crate-type = ["rlib"]

[features]
all-benchmarks = []
default        = ["petgraph"]
graph-api      = ["petgraph"]
petgraph       = ["dep:indexmap", "dep:petgraph", "dep:rand"]
telemetry      = ["hopr-api/types-telemetry"]

[dependencies]
anyhow      = { workspace = true }
bimap       = { workspace = true }
futures     = { workspace = true }
indexmap    = { workspace = true, optional = true, features = ["rayon"] }
lazy_static = { workspace = true }
parking_lot = { workspace = true }
petgraph    = { workspace = true, optional = true, features = ["rayon"] }
rand        = { workspace = true, optional = true }
smallvec    = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }

hopr-api = { workspace = true, features = ["ct", "graph", "network"] }

hopr-utils = { workspace = true, features = [
  "statistics-types",
  "statistics-types-moving",
] }

[dev-dependencies]
anyhow      = { workspace = true }
assertables = { workspace = true }
criterion   = { workspace = true }
hex-literal = { workspace = true }
insta       = { workspace = true, features = ["yaml"] }
serde       = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true }

[[bench]]
harness = false
name    = "traverse_bench"
