[package]
authors.workspace      = true
categories             = ["network-programming"]
description            = "HOPR session server that bridges TCP/UDP sockets from the Session Exit node to a destination"
edition.workspace      = true
homepage.workspace     = true
include                = ["Cargo.toml", "LICENSE", "README.md", "src/**/*.rs"]
keywords               = ["hopr", "server", "session"]
license.workspace      = true
name                   = "hopr-session-server-forwarder"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.1"

[features]
default = ["runtime-tokio"]
runtime-tokio = [
  "dep:tokio",
  "dep:tokio-retry",
  "hopr-utils/network-types-runtime-tokio",
  "hopr-utils/parallelize-runtime-tokio",
]
telemetry = ["dep:lazy_static", "hopr-api/types-telemetry"]

[dependencies]
async-trait = { workspace = true }
hopr-api = { workspace = true, features = [
  "node-session-server",
  "types-keypair",
] }
hopr-utils = { workspace = true, features = [
  "network-types",
  "parallelize",
  "parallelize-rayon",
] }
lazy_static = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = { workspace = true }
smart-default = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tokio-retry = { workspace = true, optional = true }
tracing = { workspace = true }
validator = { workspace = true }

[lib]
doctest = false
