[package]
authors.workspace      = true
categories             = ["network-programming"]
description            = "Implementation of HOPR Chain APIs using Blokli client"
edition.workspace      = true
homepage.workspace     = true
include                = ["Cargo.toml", "LICENSE", "README.md", "src/**/*.rs", "tests/**/*.rs"]
keywords               = ["chain", "ethereum", "hopr"]
license.workspace      = true
name                   = "hopr-chain-connector"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.22.2"

[features]
pix-curvy     = ["dep:babyjubjub-ec", "dep:const-hex", "dep:curvy-core"]
pix-curvy-sdk = [
  "pix-curvy",
  "dep:curvy-chain-blokli",
  "dep:curvy-sdk",
  "dep:serde",
  "dep:tokio",
]
runtime-tokio = ["hopr-utils/runtime-tokio"]
testing       = ["hopr-utils/testing-blokli"]

[dependencies]
ahash               = { workspace = true }
anyhow              = { workspace = true }
async-broadcast     = { workspace = true }
async-trait         = { workspace = true }
atomic_enum         = { workspace = true }
babyjubjub-ec       = { workspace = true, optional = true }
blokli-client       = { workspace = true }
const-hex           = { workspace = true, optional = true }
curvy-chain-blokli  = { workspace = true, optional = true }
curvy-core          = { workspace = true, optional = true }
curvy-sdk           = { workspace = true, optional = true }
dashmap             = { workspace = true }
futures             = { workspace = true }
futures-concurrency = { workspace = true }
futures-time        = { workspace = true }
moka                = { workspace = true, features = ["future", "sync"] }
parking_lot         = { workspace = true }
petgraph            = { workspace = true, features = ["graphmap", "rayon"] }
postcard            = { workspace = true }
redb                = { workspace = true }
serde               = { workspace = true, optional = true }
serde_json          = { workspace = true }
smart-default       = { workspace = true }
tempfile            = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true, optional = true }
tracing             = { workspace = true }
validator           = { workspace = true }

hopr-api = { workspace = true, features = [
  "chain",
  "node",
  "serde",
  "types-random",
  "types-with-bindings",
] }
hopr-utils = { workspace = true, features = ["runtime-tokio"] }

[dev-dependencies]
blokli-client = { workspace = true, features = ["testing"] }
const-hex = { workspace = true }
hex-literal = { workspace = true }
hopr-utils = { workspace = true, features = [
  "runtime-tokio",
  "testing-blokli",
] }
insta = { workspace = true }
lazy_static = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[lib]
doctest = false
